import { Schema } from "effect";

/**
 * A User entity representing a person in the system.
 *
 * Built with `Schema.Class` which provides:
 * - Runtime validation via `Schema.decodeUnknown(User)`
 * - Type-safe constructor via `new User({ id, name })`
 * - Automatic `_tag` discrimination for pattern matching
 *
 * @example
 * ```ts
 * // Create a user
 * const user = new User({ id: 1, name: "Alice" });
 *
 * // Validate unknown data
 * const parsed = Schema.decodeUnknownSync(User)({ id: 1, name: "Alice" });
 *
 * // Encode to plain object
 * const plain = Schema.encodeSync(User)(user);
 * ```
 */
export class User extends Schema.Class<User>("User")({
	/** Unique identifier for the user (auto-generated by UserService) */
	id: Schema.Number,
	/** Display name of the user */
	name: Schema.String,
}) {}
